### ISSUE TITLE
Elapsed time is recomputed every time prompt is redrawn

### ISSUE THREAD

**Issue by sicherha** [joknarf/nerdps1#7]
### How to reproduce
Tested with Zsh in KDE's Konsole, with the default nerdps1 configuration.
1. Run in terminal: `sleep 2`
    The *elapsed* segment shows something like `2.01s`.
2. Resize the terminal window.
    The prompt is redrawn and the *elapsed* segment is updated - now it shows something like `6.29s`.
2. Resize the terminal window once more.
    The *elapsed* segment is updated again and shows something like `13.37s`.

### Expected behaviour
The elapsed time is frozen and remains unchanged as long as no further command is executed.

### Further information
The *time* segment exhibits the same behaviour: it is updated upon every redraw.
Here, too, I believe it would be preferable not to update the *time* segment but to persistently show the frozen wall clock at the time the last command finished.

**Comment by joknarf** [comment]
Hello, yes, I can reproduce the issue.
The pb is that the shell is re-evaluating the PS1, and I have no way to figure out if it is because of resize or empty command entered.
Therefore the only thing I can do is to not display the elapsed segment in case of resize (like empty command entered) 
=> the elapsed segment will disappear on the current prompt when resize, (which seems less confusing than increasing the time.)
And I cannot freeze the time segment, either.
=> resizing will display a new prompt like an empty command line has been entered.

Ok, for you ?

**Comment by joknarf** [comment]
see PR: https://github.com/joknarf/nerdps1/pull/8

**Comment by sicherha** [comment]
At least for Zsh, it should be possible to save the current uptime (`$(ps1_get_mseconds)`) and wall clock (`$(print -P %T)`) into variables inside `ps1_precmd`. Then inside `ps1_elapse` and `ps1_prompt`, these calls could be replaced with accesses to these variables.

However, since `ps1_precmd` is specific to Zsh, I don't know how this would affect all the other shells.

**Comment by joknarf** [comment]
ok, should work, see the PR updated

**Comment by joknarf** [comment]
ok,  resolved, don't forget to star the repository, as you are now contributor 😉
